name: ✏️ Run PR Title Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main, stage]

jobs:
  validate-title:
    name: ✏️ Validate PR Title
    uses: nenoyago/.github/.github/workflows/pr-title-validation.yml@main
